apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/podkrepi-bg/frontend:v0.9.0
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_URL
            value: https://podkrepi.bg
          - name: API_URL
            value: https://podkrepi.bg
