apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podkrepibg

resources:
- ../../base

patches:
- path: keycloak-config-web.patch.yaml
- path: deployment.patch.yaml

images:
- name: ghcr.io/podkrepi-bg/frontend
  newTag: v0.9.3
- name: ghcr.io/podkrepi-bg/frontend/maintenance
  newTag: master
