version: '3'
services:
  frontend:
    image: ghcr.io/daritelska-platforma/frontend/web:${DEPLOY_TAG}
    container_name: app-frontend-prod
    restart: always
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3

    networks:
      pub1:
        ipv4_address: ${HOST_IPV4_ADDRESS}

networks:
  pub1:
    external: true
