version: '3'
services:
  app:
    image: ghcr.io/daritelska-platforma/frontend/web:deployment-changes
    container_name: app-frontend-prod
    restart: always
    networks:
      pub1:
        ipv4_address: 172.14.0.4
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
networks:
  pub1:
    external: true
