version: '3.7'
services:
  frontend:
    image: ${COMPOSE_PROJECT_NAME?}-frontend
    container_name: ${COMPOSE_PROJECT_NAME?}-frontend

    environment:
      API_URL: ${API_URL}
      APP_URL: ${APP_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      JWT_SECRET: ${JWT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}

    networks:
      - frontend-net

    healthcheck:
      test: curl --fail http://localhost:3040/api/healthcheck || exit 1
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  frontend-net:
    driver: bridge
