version: '3.7'
services:
  frontend:
    container_name: ${COMPOSE_PROJECT_NAME?}-frontend

    build:
      context: ./
      dockerfile: ./Dockerfile
      target: ${TARGET_ENV}
      args:
        NODE_ENV: ${NODE_ENV}
    image: ${COMPOSE_PROJECT_NAME?}-frontend
    ports:
      - '${APP_PORT}:3040'

    # volumes:
    #   # Local:Container mounting points
    #   - ./src:/app/src
    #   - ./public:/app/public
    #   - ./node_modules:/app/node_modules
    #   - ./.next:/app/.next

    environment:
      API_URL: ${API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      JWT_SECRET: ${JWT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}

    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge
