version: '3.7'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: ${TARGET_ENV}
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - '${APP_PORT}:3040'
    volumes:
      # Local:Container mounting points
      - ./src:/app/src
      - ./public:/app/public
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next

  api:
    build:
      context: ./backend/contact
      dockerfile: ./Dockerfile
      target: ${TARGET_ENV}
    environment:
      DEBUG: 'true'
    ports:
      - '5000:5000'
    volumes:
      - ./backend/contact:/app

networks:
  frontend-net:
    driver: bridge
