version: '3.7'
# Override service props from main `docker-compose.yml`
services:
  frontend:
    networks:
      pub1:
        ipv4_address: ${FRONTEND_IPV4_ADDRESS?}

  api:
    networks:
      pub1:
        ipv4_address: ${API_IPV4_ADDRESS?}

networks:
  pub1:
    external: true
