version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: production
    container_name: app-frontend-staging
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    ports:
      - '3041:3040'
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
networks:
  app-network:
    driver: bridge
