version: '3.8'
services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME?}-frontend

    build:
      context: ./
      dockerfile: ./Dockerfile
      target: ${TARGET_ENV}
      args:
        NODE_ENV: ${NODE_ENV}

    ports:
      - '${APP_PORT}:3040'

    volumes:
      # Local:Container mounting points
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
      - /app/.next

    environment:
      API_URL: ${API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      JWT_SECRET: ${JWT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}

    networks:
      - net-frontend

networks:
  net-frontend:
    driver: bridge
