apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: podkrepi-frontend
      docker:
        dockerfile: Dockerfile
        target: production
deploy:
  kubectl:
    manifests:
      - kubernetes/podkrepi-dev-namespace.yaml
      - kubernetes/cockroachdb.yaml
      - kubernetes/frontend-deployment.yaml
      - kubernetes/frontend-net-networkpolicy.yaml
      - kubernetes/frontend-service.yaml
    defaultNamespace: podkrepi-dev

portForward:
  - resourceType: Service
    resourceName: frontend
    namespace: podkrepi-dev
    port: 3040
    localPort: 3040
