# https://taskfile.dev

version: '3'

tasks:
  lint:
    desc: Lint module
    silent: false
    cmds:
      -  golangci-lint run

  watch:
    desc: Run module
    silent: false
    cmds:
      - go get github.com/githubnemo/CompileDaemon
      - CompileDaemon --build="go build -o output/accounts ." --command=./output/accounts

  build:
    desc: Build module
    silent: false
    cmds:
      - go build -o output/accounts .
    sources:
      - ./**/*.go
      - go.mod
    generates:
      - output/accounts
    method: checksum
