blank_issues_enabled: true
contact_links:
    - name: Ask Question
      url: https://github.com/daritelska-platforma/frontend/discussions
      about: Ask questions
    - name: Join Discord
      url: https://discord.gg/pwkfzvPBSm
      about: Discuss with other community members
