---
apiVersion: v1
kind: Service
metadata:
  name: frontend-headless
  namespace: frontend
spec:
  selector:
    app: frontend
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 3040
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/podkrepi-bg/frontend/web:test
        env:
        - name: NODE_ENV
          value: production
        - name: TARGET_ENV
          value: production
        - name: APP_ENV
          value: production
        - name: APP_URL
          value: https://dev.podkrepi.bg
        - name: APP_PORT
          value: "3040"
        - name: API_URL
          value: http://contact-headless.contact.svc
        - name: REST_API_PORT
          value: "80"
        ports:
        - containerPort: 3040
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3040
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3040
          initialDelaySeconds: 5
          periodSeconds: 5
