name: Test backend

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run contact tests
      working-directory: backend/contact
      run: go test -v -race ./...