name: Next.js build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - "frontend/**"

jobs:
  build-codebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --cwd frontend
        # if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Build frontend
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          cp .env.example ./frontend/.env
          yarn build --cwd frontend
