name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  build-codebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Setup environment
        run: cp .env.example .env

      - name: Build frontend
        run: yarn build
