name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build frontend
        run: yarn build
