name: Build contact

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - "backend/contact/**"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Lint 
      uses: golangci/golangci-lint-action@v2
      with:
        working-directory: ./backend/contact
        version: v1.32
        args: --timeout=3m0s

    - name: Run tests
      working-directory: ./backend/contact
      run: go test -v -race ./...