name: Build docker image

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  build-pr:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: frontend

    steps:
      - uses: actions/checkout@v2

      - name: Build frontend
        run: |
          docker build . \
            --file ./Dockerfile \
            --target production \
            --build-arg NODE_ENV=production \
            --tag $IMAGE_NAME \
            --tag $IMAGE_NAME:ci-run
