name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint frontend
        run: yarn lint

      - name: Lint styles
        run: yarn lint:styles
