name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Lint frontend
        run: yarn lint

      - name: Lint styles
        run: yarn lint:styles
