name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  run-jest:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run: yarn test --ci
